### ISSUE TITLE
setex() got an unexpected keyword argument 'key'

### ISSUE THREAD

**Issue by FVolral** [sfer033/quart-session#4]
Hello, I got the following error when using quart-session :

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/Quart-0.13.1-py3.9.egg/quart/app.py", line 1824, in handle_request
    return await self.full_dispatch_request(request_context)
  File "/usr/local/lib/python3.9/site-packages/Quart-0.13.1-py3.9.egg/quart/flask_patch/app.py", line 30, in new_full_dispatch_request
    return await old_full_dispatch_request(self, request_context)
  File "/usr/local/lib/python3.9/site-packages/Quart-0.13.1-py3.9.egg/quart/app.py", line 1847, in full_dispatch_request
    return await self.finalize_request(result, request_context)
  File "/usr/local/lib/python3.9/site-packages/Quart-0.13.1-py3.9.egg/quart/app.py", line 1909, in finalize_request
    response = await self.process_response(response, request_context)
  File "/usr/local/lib/python3.9/site-packages/Quart-0.13.1-py3.9.egg/quart/app.py", line 1939, in process_response
    await self.save_session(session_, response)
  File "/usr/local/lib/python3.9/site-packages/Quart-0.13.1-py3.9.egg/quart/app.py", line 1472, in save_session
    await self.ensure_async(self.session_interface.save_session)(self, session, response)
  File "/usr/local/lib/python3.9/site-packages/quart_session/sessions.py", line 172, in save_session
    await self.set(key=session_key, value=val, app=app)
  File "/usr/local/lib/python3.9/site-packages/quart_session/sessions.py", line 240, in set
    return await self.backend.setex(
TypeError: setex() got an unexpected keyword argument 'key'
```

I'm not doing something special : 

```
app.config['SESSION_TYPE'] = 'redis'
app.config['SESSION_REDIS'] = Redis(host="redis-service", port=6379)
app.config['SESSION_PROTECTION'] = True

...

 # This error happens when I try to reach this route:
@app.route('/set/') 
def set():
    session['check'] = 'value'
    return 'ok'
```

I tried to connect to redis with an another python instance and it worked with the same parameters. Also Quart doesn't complain if I use random value for  SESSION_REDIS but I'm not sure it is linked. 

Tell me if you need more info.

**Comment by sfer033** [comment]
[doc](https://github.com/sfer033/quart-session/blob/master/README.md#redis-support) specifies that you need to pass it a `aioredis.Client` instance. Are you using `redis` instead? This will not work.
